/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  http: {
    Auth: () => import('#controllers/http/auth_controller'),
    Companies: () => import('#controllers/http/companies_controller'),
    Users: () => import('#controllers/http/users_controller'),
  },
}
