/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CompanySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'isActive', 'name', 'slug', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RefreshTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'isRevoked', 'token', 'updatedAt', 'userId'] as const
  $columns = RefreshTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isRevoked: boolean
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: bigint | number
}

export class UserSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'createdBy', 'deletedAt', 'email', 'id', 'isActive', 'isMaster', 'lastLoginAt', 'name', 'password', 'role', 'token', 'updatedAt', 'updatedBy'] as const
  $columns = UserSchema.$columns
  @column()
  declare companyId: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: bigint | number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isActive: boolean
  @column()
  declare isMaster: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare token: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: bigint | number | null
}
